// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkPmdm0ZzKPM39GkNGk1vbGA47MXHQeQM',
    appId: '1:263796362022:web:cbec9d3be06c06f9c14fe7',
    messagingSenderId: '263796362022',
    projectId: 'emotional-dairy-b3cc0',
    authDomain: 'emotional-dairy-b3cc0.firebaseapp.com',
    storageBucket: 'emotional-dairy-b3cc0.firebasestorage.app',
    measurementId: 'G-VQMREY1ZKK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmtvBOHataIcbdB4xLLavg1dMVVFfVL4o',
    appId: '1:263796362022:android:e2145ffc9eca3f2fc14fe7',
    messagingSenderId: '263796362022',
    projectId: 'emotional-dairy-b3cc0',
    storageBucket: 'emotional-dairy-b3cc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAw-9Q0upC3VpttHRDeTJD5hnmr4SQzIg',
    appId: '1:263796362022:ios:060e5bd489afad9ac14fe7',
    messagingSenderId: '263796362022',
    projectId: 'emotional-dairy-b3cc0',
    storageBucket: 'emotional-dairy-b3cc0.firebasestorage.app',
    iosClientId: '263796362022-6nn80vbqpjfa7kf28s0osupnrq87cof9.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionalDairy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAw-9Q0upC3VpttHRDeTJD5hnmr4SQzIg',
    appId: '1:263796362022:ios:060e5bd489afad9ac14fe7',
    messagingSenderId: '263796362022',
    projectId: 'emotional-dairy-b3cc0',
    storageBucket: 'emotional-dairy-b3cc0.firebasestorage.app',
    iosClientId: '263796362022-6nn80vbqpjfa7kf28s0osupnrq87cof9.apps.googleusercontent.com',
    iosBundleId: 'com.example.emotionalDairy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkPmdm0ZzKPM39GkNGk1vbGA47MXHQeQM',
    appId: '1:263796362022:web:a9e4ce310d80e9edc14fe7',
    messagingSenderId: '263796362022',
    projectId: 'emotional-dairy-b3cc0',
    authDomain: 'emotional-dairy-b3cc0.firebaseapp.com',
    storageBucket: 'emotional-dairy-b3cc0.firebasestorage.app',
    measurementId: 'G-7NSFXLCF57',
  );
}
